version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      # srcはphp側で管理
      #- ./html:/var/www/html/ php側で管理
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # localhostがconflictするのでゲスト側のdefault.confを書き換えるようにする。
    ports: 
      - "8081:80"
    depends_on:
      - php
  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html/
